apiVersion: v1
kind: Service
metadata:
  # Match the hostname in application.properties
  name: vprodb
spec:
  # Default type: clusterIP
  selector:
    app: vprodb-pod
  ports:
  - port: 3306
    targetPort: vprodb-port
    # Default protocol: TCP