apiVersion: v1
kind: Service
metadata:
# Match the hostname in application.properties
  name: vprocache01
spec:
  # Default type: clusterIP
  selector:
    app: vpromc-pod
  ports:
    - port: 11211
      targetPort: vpromc-port
      # Default protocol: TCP